### ISSUE TITLE
Using Remodal with AJAX

### ISSUE THREAD

**Issue by amilajack** [VodkaBears/Remodal#101]
I'm trying to use AJAX to load in HTML from the server, append it the modal and open it. This is the code in my local environment:
```
function getItemView(itemId) {
			$.ajax({
				type: "GET",
				url: '/item/view/' + itemId
			})
			.done(function(d) {
				// Close modal if already open
				$('#remodal-item-view-content').html(d);
				$('[data-remodal-id=itemView]').remodal({hashTracking: false}).open();
			});
		}
```
This works perfectly in my local env. However, when I push it to production, the modal fails to open. I checked that the html is being appended. It only works when I use the following code:
```
...
.done(function(d) {
			// Close modal if already open
			$('#remodal-item-view-content').html(d);
			// NEED THIS TIMEOUT IN PRODUCTION
			setTimeout(function() {
                    $('[data-remodal-id=itemView]').remodal().open();
            }, 1000)
		});
...
```
Without the timeout, the modal will not open. Any ideas why this is happening? Thanks!

**Comment by VodkaBears** [comment]
Maybe DOM content was not loaded.
Wrap it:
```js
$(document).ready(function() {
  ...
});
```

**Comment by amilajack** [comment]
Never mind. I was doing something stupid. I was closing the modal just in case if the modal was already open and then opening it right after. In my local env it worked but idk why it didnt in production.

Thanks for the amazing plugin btw! Using it on fertona.com! Its definitely a crucial part of the experiene
