### ISSUE TITLE
Help on ipad

### ISSUE THREAD

**Issue by amitgur** [VodkaBears/Remodal#104]
Hello 
I'm using modal and it working great exept on my IPAD2 browsers (chrome/safari) anybody have an idea way? I'm using 0.6.4 and opening like this :

    <a data-remodal-target="modal">Call the modal with data-remodal-id="modal"</a>

**Comment by VodkaBears** [comment]
Hi!

http://stackoverflow.com/questions/3705937/document-click-not-working-correctly-on-iphone-jquery/17490775#17490775.

**Comment by VodkaBears** [comment]
Also, you can simple set the `href` attribute with the number sign.
