### ISSUE TITLE
Error on close

### ISSUE THREAD

**Issue by zanonnicola** [VodkaBears/Remodal#108]
Hi there,

I'm using the plugin in combination with ouibounce (https://github.com/carlsednaoui/ouibounce#cookie-domain).
I'm getting a strange error every time I close the modal:

Uncaught TypeError: Cannot read property 'open' of undefined

I'm using this method to call the modal:
```
$('[data-remodal-target=modal]').remodal(options).open();
```

Any idea?
This is the link: http://www.ignitehospitality.com/temp_hosting/dev/
Just hover over the navigation bar when the page is loaded.

Thanks in advance!

**Comment by VodkaBears** [comment]
You should use: `[data-remodal-id=modal]`

**Comment by VodkaBears** [comment]
`data-remodal-target` is used for the links only.

**Comment by zanonnicola** [comment]
Thanks @VodkaBears that works but it leaves the hash on the URL so when you click the back button it triggers the modal again even if "hashTracking" is set to false.

**Comment by VodkaBears** [comment]
Sure? `data-remodal-options="hashTracking: false"`. It is not set on your page.

```js
<div class="remodal" data-remodal-id="modal" data-remodal-options="hashTracking: false">
```

Options are unneccesary -> `$('[data-remodal-id=modal]').remodal().open();`.

**Comment by VodkaBears** [comment]
In your case `$('[data-remodal-id=modal]').remodal()` returns the modal without the re-creation.

**Comment by zanonnicola** [comment]
@VodkaBears thanks for the clarification! It works like a charm now! 
Great plugin by the way!
