### ISSUE TITLE
Avoid scroll on top?

### ISSUE THREAD

**Issue by stephjiayi** [VodkaBears/Remodal#110]
Is it possible to avoid the automatic scrolling on top when the modal is triggered although I disabled hashTracking?

**Comment by VodkaBears** [comment]
It scrolls to the top only the inner content.

**Comment by VodkaBears** [comment]
Example?

**Comment by stephjiayi** [comment]
Sorry it was my fault, after several tries I understood that the problem was caused by "overflow-y: scroll" applied to the body. Anyway please accept my apologies and thank you for your support.

**Comment by VodkaBears** [comment]
No problems.
