### ISSUE TITLE
Issue calling iframe with google map

### ISSUE THREAD

**Issue by spetrini** [VodkaBears/Remodal#111]
Using the below code the modal opens but the map will not display correctly. While the modal is open if I refresh, the map then display correctly, any thoughts?

[a href="#show1"]Open Map[a]

[div class="remodal" data-remodal-id="show1"]
[iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26432.433958227946!2d-118.32647809999999!3d34.0937508!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2bf07045279bf%3A0xf67a9a6797bdfae4!2sHollywood%2C+Los+Angeles%2C+CA!5e0!3m2!1sen!2sus!4v1429631619418" width="600" height="450" frameborder="0" style="border:0"][/iframe]
[/div]

**Comment by VodkaBears** [comment]
As a suggestion, you can insert it on the first call.

```js
  $(document).one('open', '[data-remodal-id="show1"]', function (e) {
    $(e.target).html('<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26432.433958227946!2d-118.32647809999999!3d34.0937508!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2bf07045279bf%3A0xf67a9a6797bdfae4!2sHollywood%2C+Los+Angeles%2C+CA!5e0!3m2!1sen!2sus!4v1429631619418" width="600" height="450" frameborder="0" style="border:0"></iframe>')
  });
```

**Comment by spetrini** [comment]
Well I seem to have a problem getting this to open, must have something wrong.
    
    <script>
    $(document).one('open', '[data-remodal-id="show1"]', function (e) {
     $(e.target).html('<iframe width="600" height="400" allowtransparency="true" frameborder="0" scrolling="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26432.433958227946!2d-118.32647809999999!3d34.0937508!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2bf07045279bf%3A0xf67a9a6797bdfae4!2sHollywood%2C+Los+Angeles%2C+CA!5e0!3m2!1sen!2sus!4v1429631619418"></iframe>')
    });
    </script>


    <a data-remodal-target="modal" href="show1">View Map</a>


    <div data-remodal-id="show1">...</div>

**Comment by VodkaBears** [comment]
You should add the class to initialize it, when DOM is ready:
```html
<div class="remodal" data-remodal-id="show1">...</div>
```

Or:

```js
$('[data-remodal-id="show1"]').remodal();
```

**Comment by spetrini** [comment]
I appreciate you taking your time to comment.
I had already tried it with that class and it still wont show the modal. 
I'm calling it from ahref like so, do you see any issue here?

     <a data-remodal-target="modal" href="show1">View Map</a>

**Comment by VodkaBears** [comment]
Yes)
```js
 <a href="#show1">View Map</a>

//Or
 <a data-remodal-target="show1">View Map</a>
```

**Comment by spetrini** [comment]
That was it...works now...but I seem to have lost my X to close the modal

**Comment by spetrini** [comment]
Figured it out, thanks again and great script!
