### ISSUE TITLE
Return data from remodal

### ISSUE THREAD

**Issue by Cam1337** [VodkaBears/Remodal#119]
Hi,

Is there a way to return data from a remodal that does not involve global variables? I am looking for something similar to this:  
```javascript
var inst = $("[data-remodal-id=modal2]").remodal();
var data = inst.open();

or

 $(document).on("closed", ".remodal", function (e) {
   // handle data (but only e is passed :( )
});
```

**Comment by VodkaBears** [comment]
`var inst = $("[data-remodal-id=modal2]").remodal();`

It is possible right now :)
