### ISSUE TITLE
Issue trying use font-awesome

### ISSUE THREAD

**Issue by danielfpedro** [VodkaBears/Remodal#120]
Something in your code is forcing some font so font-awesome is not working inside your modal until I do it.

No working:
`<span class="fa fa-pencil"></span>`

Working with hack:
`<span class="fa fa-pencil" style="font-family: font-awesome!important"></span>`

**Comment by VodkaBears** [comment]
Delete the first CSS line. Fonts will be removed completely in v1.0.0.
