### ISSUE TITLE
Prevent modal opening through 'back' history?

### ISSUE THREAD

**Issue by Tasemu** [VodkaBears/Remodal#128]
When you open and close the modal, it will re-open when you try to navigate back to the previous page. Is there any way currently implemented to avoid this without putting in my own fix?

**Comment by VodkaBears** [comment]
It is because of the hash. Set `hashTracking: false`.

**Comment by Tasemu** [comment]
I'm actually getting no love from that, I have changed the hashtracking and the issue has not changed at all.

**Comment by VodkaBears** [comment]
You are doing it wrong.

**Comment by VodkaBears** [comment]
https://github.com/VodkaBears/Remodal#options

**Comment by CoteViande** [comment]
`hashTracking: false` does not seem to work with href="#modal" but only with data-remodal-target="modal"

**Comment by VodkaBears** [comment]
> Unless I'm also doing it wrong, hashTracking: false does not seem to work with href="#modal" but only with data-remodal-target="modal"

Yes, it works only with `data-remodal-target`, because `hashTracking: false` means that the hash tracking is off, so any changes of the hash will be ignored :)

**Comment by CoteViande** [comment]
Everything is working fine like this :) Thanks for the plugin by the way!
