### ISSUE TITLE
closeOnEscape does not work with multiple controls on one page

### ISSUE THREAD

**Issue by jimmyfo** [VodkaBears/Remodal#130]
When different divs are tagged as modal popups on the same page, the "closeOnEscape" remodal option cannot be set. For example, two divs, both are remodal, displayed with two separate clicks.

`div class="remodal task-details" data-remodal-id="modal-task-details">...</div>`

And

`<div class="remodal appointmentSlotEditor calendarPageDialog" data-remodal-id="editAppointmentSlotModal">...</div>`

When trying to assign the following options to ONE of the divs above:

data-remodal-options='{ "closeOnAnyClick": false, "closeOnEscape": false }'

the option closeOnEscape does not work. It will close the modal, but the screen becomes disabled and the '#editAppointmentSlotModal' stays in the URL. It appears that this gets fired twice:

    // Add the keyboard event listener
    $(document).on('keyup.' + namespace, function(e) {
      if (e.keyCode === 27 && remodal.settings.closeOnEscape) {
        remodal.close();
      }
    });

When BOTH divs have the same options, it works. But they cannot have different options.

This appears to be a bug. Thoughts?

**Comment by VodkaBears** [comment]
> data-remodal-options='{ "closeOnAnyClick": false, "closeOnEscape": false }'
It is an old unsupported syntax. You should write: `data-remodal-options="closeOnOutsideClick: false, closeOnEscape: false"`

**Comment by jimmyfo** [comment]
Is that for 0.6.4? The issue is still there and the option "closeOnOutsideClick" does not occur in that release or in the documentation.

**Comment by VodkaBears** [comment]
> Is that for 0.6.4? The issue is still there and the option "closeOnOutsideClick" does not occur in that release or in the documentation.

closeOnAnyClick, i've corrected. closeOnOutsideClick will be in v1.0.0.

**Comment by VodkaBears** [comment]
Ok, this one will be fixed in the v1.0.0.

**Comment by VodkaBears** [comment]
https://github.com/VodkaBears/Remodal/releases/tag/1.0.0
