### ISSUE TITLE
hashTracking not working

### ISSUE THREAD

**Issue by jlcd** [VodkaBears/Remodal#138]
Hi, I've tried using `data-remodal-options="hashTracking: false`, `REMODAL_GLOBALS` and `{ hashTracking: false }`. Nothing seems to be stopping the modal to open when there's a hash.
Can you please confirm?

My current code:

       $('[data-open-form]').click(function (e) {
                    e.preventDefault();

                    var $this = $(this);

                    $modalForm.remodal({ hashTracking: false }).open();
                    (...)
        }

With this, when I go to http://MYURL/#modal-hash, the modal opens automatically.

**Comment by VodkaBears** [comment]
If you initialize it with javascript, do you remove `remodal` class from the node? https://github.com/VodkaBears/Remodal#initialization-with-javascript.

```js
$modalForm.remodal({ hashTracking: false }).open();
```

Globals work. Do you have the latest version? There is already v1.0.0.
```js
window.REMODAL_GLOBALS = {
  DEFAULTS: {
    hashTracking: false
  }
};
```

**Comment by jlcd** [comment]
Sorry, forgot to mention. 
I'm actually on `Remodal - v1.0.1`. Should I use v1.0.0 instead?

**Comment by VodkaBears** [comment]
Globals should be add before you include the library.
https://github.com/VodkaBears/Remodal#globals

**Comment by jlcd** [comment]
True. That did it.
Thanks!

Just a heads up: it's not working when using `data-remodal-options="hashTracking: false`or `{ hashTracking: false }`.

**Comment by VodkaBears** [comment]
> Just a heads up: it's not working when using data-remodal-options="hashTracking: false"or { hashTracking: false }.

Let's investigate. For me it works. Are there any errors in the console?

**Comment by VodkaBears** [comment]
`$modalForm.remodal({ hashTracking: false })`

Are you sure that you initialize it only in this place? It takes arguments only for the first call, then it returns the instance.

**Comment by jlcd** [comment]
This is what I'm doing:

                $modalForm.remodal({ hashTracking: false });

                $('[data-open-form]').click(function (e) {
                    e.preventDefault();

                    var $this = $(this);

                    $modalForm.remodal().open();

                    (...)

**Comment by VodkaBears** [comment]
I'm confused.
90% that you initialize it without options somewhere. Please, check it carefully.

Is node without the `.remodal` class right now? If you set the class for the node, it will be auto-initialized.

**Comment by jlcd** [comment]
Oh man, I'm embarrassed :(

Just found another `$modalForm.remodal()` where there shouldn't be one. Didn't realize it was there at first... totally my fault.
Sorry for calling this a bug.

**Comment by VodkaBears** [comment]
Hah, no problems, closed.
