### ISSUE TITLE
Using different animations with modal

### ISSUE THREAD

**Issue by simsketch** [VodkaBears/Remodal#140]
Is there an easy way to pass in a modifier to change the animation to a growIn or something other than the awesome animation it currently uses?

**Comment by simsketch** [comment]
Didn't realize all I had to do was jump in the CSS file and change my animation as needed.  Thanks so much!

**Comment by webfolkcreative** [comment]
@simsketch Did you have an example of the animation you swapped to? Looking to change out the animation as well, and just wondering how you went about it/what you changed it to? Cheers!
