### ISSUE TITLE
Open Remodal from external links

### ISSUE THREAD

**Issue by Hydra9268** [VodkaBears/Remodal#142]
Hi. Is it possible to do this? Would like to trigger it from source outside the website.

**Comment by VodkaBears** [comment]
?

**Comment by Hydra9268** [comment]
I would like to trigger the remodal from a link on another website. Is it possible to do this?

**Comment by VodkaBears** [comment]
> I would like to trigger the remodal from a link on another website. Is it possible to do this?

Yes, a correct hash will open it.

**Comment by Hydra9268** [comment]
Awesome!

Am I correct in concluding that if data-remodal-options="hashTracking: false" is used this will basically make remote launching of the modal not possible?

**Comment by Hydra9268** [comment]
Awesome!

Am I correct in concluding that if data-remodal-options="hashTracking: false" is used this will basically make remote launching of the modal not possible?

The hashtag was disabled on the target site because of the browser's back button. When pressing the back button this relaunches the modal which was breaking the navigation.

Anyhow thanks for your help. :)

**Comment by VodkaBears** [comment]
> Am I correct in concluding that if data-remodal-options="hashTracking: false" is used this will basically make remote launching of the modal not possible?

Lol, "remote launching" sounds great like some kind of hacker stuff. Yes, "hashTracking: false" disables the hash navigation, but why not check some url-param and open a modal after page load?
