### ISSUE TITLE
Unique hashes - one modal

### ISSUE THREAD

**Issue by lotestudio** [VodkaBears/Remodal#145]
Excellent modal! Like it very much!
I want to load ajax content in modal using different hashes with only one modal markup.
For example "#modal-1","#modal-2"...
Is there way to do this or extend with some similar functionality.
Thanks again!

**Comment by VodkaBears** [comment]
> Excellent modal! Like it very much!
I want to load ajax content in modal using different hashes with only one modal markup.
For example "#modal-1","#modal-2"...
Is there way to do this or extend with some similar functionality.
Thanks again!

The simplest solution is to create 2 different modals. But if you don't want, you can disable the hash navigation(`hashTracking: false`) and make your own implementation. Then just put your loaded content into the DOM element of the modal.

**Comment by VodkaBears** [comment]
Also i should say that you can change the whole markup in the modal (with modal controls) at any time.

**Comment by lotestudio** [comment]
Thanks for the answer. Here is my quick implementation. I'll be glad to see something like this in next releases.

	<html>
	<head>
		<meta charset="UTF-8">
		<title>Remodal hash changer</title>
		<link href='//fonts.googleapis.com/css?family=Roboto:400,100,400italic,700italic,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="bower_components/remodal/dist/remodal.css">
		<link rel="stylesheet" href="bower_components/remodal/dist/remodal-default-theme.css">
		<style>
			body{
				font-family: Roboto;
				font-weight: 100;
				margin:100px;
			}
		</style>
	</head>
	<body>

		<a href="#modal=about.html">Call the modal with url=about</a>
		<br>
		<a href="#modal=contact.html">Call the modal with url=contact</a>

		<div class="remodal" data-remodal-id="modal">
			<button data-remodal-action="close" class="remodal-close"></button>
			<div id="remodalcontent">
					Loading...
			</div>
		</div>
	</body>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script>
		window.REMODAL_GLOBALS = {
			DEFAULTS: {
				hashTracking: false
			}
		};
	</script>
	<script src="bower_components/remodal/dist/remodal.min.js"></script>
	<script>
		//prototype string start
		if (typeof String.prototype.startsWith != 'function') {
			String.prototype.startsWith = function (str){
				return this.slice(0, str.length) == str;
			};
		}
		//handle hash change
		if ("onhashchange" in window) { // event supported?
			window.onhashchange = function () {
				hashChanged(window.location.hash);
			}
		}
		else { // event not supported:
			var storedHash = window.location.hash;
			window.setInterval(function () {
				if (window.location.hash != storedHash) {
					storedHash = window.location.hash;
					hashChanged(storedHash);
				}
			}, 100);
		}
		//instance of remodal
		var inst = $('[data-remodal-id=modal]').remodal();

		//hashChage handler
		function hashChanged(hash){
			//console.log("hash: "+hash);
			if(hash.startsWith("#modal")){
				var url = hash.split('=')[1];
				//... load content from url via ajax and add to remodal container...
				$('#remodalcontent').html(url);//for example only...
				inst.open();
			}else{
				var state = inst.getState();
				//console.log("state: "+state);
				if(state=="opening" || state=="opened"){
					inst.close();
				}
			}
		}
		//clear hash
		function removeHash () {
		    history.pushState("", document.title, window.location.pathname+window.location.search);
		}
		//fire when landing on the page
		hashChanged(window.location.hash);

		//clear hash and html on close
		$(document).on('closed', '.remodal', function (e) {
			removeHash();
			$('#remodalcontent').html('Loading...');
		  	// Reason: 'confirmation', 'cancellation'
		  	//console.log('Modal is closed' + (e.reason ? ', reason: ' + e.reason : ''));
		});

	</script>
	</html>
