### ISSUE TITLE
Why remodal doesn't work with IE9

### ISSUE THREAD

**Issue by kodjoe** [VodkaBears/Remodal#146]
Hello there is a way to have remodal on ie9 ?

I try your link on browserstack.com, with windows 7 and IE9 and the link open nothing ?
can you help please.

-> http://www.jqueryscript.net/demo/Responsive-Flat-jQuery-Modal-Plugin-with-CSS3-Transitions-Remodal/

**Comment by VodkaBears** [comment]
It is not my link.

The page below has the version 0.1.0... The problem is `console.log` in the code of the page, it is the "feature" of IE8, IE9 (http://stackoverflow.com/a/5473193). Remodal works in IE8+ and, please, use the latest version.

**Comment by kodjoe** [comment]
thank you guy ;D
