### ISSUE TITLE
Keyboard navigation accessibility issue

### ISSUE THREAD

**Issue by Dan503** [VodkaBears/Remodal#147]
If you are using a keyboard to navigate the site, you click on the remodal trigger and it opens the remodal box. 

If there are links inside the remodal box and you try to tab to them, you instead tab to the very first link on the page, not the first link inside the remodal box. You can *eventually* tab to the links inside the remodal box but you have to tab through every single link on the page before you can get there. If it's not an accessibility issue then it's a horrible usability issue.

Focus should be given to an invisible link at the top of the remodal box when it opens so you can tab directly to the next link that is inside the remodal box with a single press of the tab key.

**Comment by VodkaBears** [comment]
> Focus should be given to an invisible link at the top of the remodal box when it opens so you can tab directly to the next link that is inside the remodal box with a single press of the tab key.

No, it will be a bit harder. I know only JS solution with events.

**Comment by Dan503** [comment]
It's not that hard. Elements can only recieve focus if they are actually focusable which is why I suggested an empty link.

If you don't like the idea of an empty link, how about this?

1. When box opens, create empty div element with a tabindex="0" attribute on it just before the remodal content div so it doesn't interfere with the developers content.
2. Apply focus to that empty div when the box has finished opening (remove any :focus styling that is on the element)
3. When that empty div loses focus (as in on blur) it is removed or maybe just hidden so the user can't tab back to it.

**Comment by VodkaBears** [comment]
This solution does not limit focusable elements on a page when a modal is opened.

**Comment by Dan503** [comment]
I don't think it *needs* to prevent people from being able to tab to background elements. The box is already at the bottom of the page and people hardly ever tab backwards so they are highly unlikely to tab to the background elements any way.

It's *far* better usability than the current implementation of having to tab a million times to get to links inside the box.

I've done that technique using the remodal "on open" callback function and it works great. I just wish it came as a default feature so I don't have to write the code out all the time for a basic accessibility feature.
