### ISSUE TITLE
Modals with Forms Freeze on iOS

### ISSUE THREAD

**Issue by fny** [VodkaBears/Remodal#150]
Seems related to #96.

It locks up if the user ever taps "Done"

![test2](https://cloud.githubusercontent.com/assets/346068/8489264/b7214f16-20e7-11e5-9ec8-f2822e9ebed6.gif)

The screen also jumps like crazy when moving between inputs:

![untitled](https://cloud.githubusercontent.com/assets/346068/8489268/baa6a794-20e7-11e5-83ae-3d2b8b40e692.gif)

**Comment by VodkaBears** [comment]
Have you tested it on a device? I don't have freezing in iOS 8.

**Comment by VodkaBears** [comment]
Closed in favor of issue #96
