### ISSUE TITLE
Problem with select2

### ISSUE THREAD

**Issue by Mowso** [VodkaBears/Remodal#151]
Hi !

I'm using remodal and I'm experiencing some troubles trying to use select2 plugin in it. Is there a way to solve it? I just would like to have a drop down menu in a pop up.
![capture d ecran 2015-07-03 a 12 26 04](https://cloud.githubusercontent.com/assets/6728213/8497607/e26e5b7c-217e-11e5-915b-39eb89cd6f54.png)

**Comment by johnsudaar** [comment]
Same issue here.
Can you make your z-index less extreme here.
https://github.com/VodkaBears/Remodal/blob/master/src/remodal.css#L35
It's working fine with 1000 (since select2 is using 1051)

**Comment by VodkaBears** [comment]
> Can you make your z-index less extreme here.

I can't. The version is stable. No incompatible changes since 1.0.

**Comment by phsantosti** [comment]
> This worked for me
> 
> ```css
> .remodal-wrapper {
>   z-index: 1000;
> }
> 
> .remodal-overlay {
>   z-index: 999;
> }
> ```

Is Working Nice! Thanks
