### ISSUE TITLE
Prevent closing modal on clicking outside of modal (anywhere on the body)

### ISSUE THREAD

**Issue by creativesoumik** [VodkaBears/Remodal#16]
is there any way to prevent closing the modal by clicking on outside of the modal? i want the user to click on the close button in order to close the modal.

**Comment by damiani** [comment]
Note that both of these bindings have changed; since version 1.0.2, they should be:
```javascript
$(document).ready(function () {
    $('.remodal-wrapper').unbind('click.remodal');
});
```
and
```javascript
$(document).unbind('keydown.remodal');
```
