### ISSUE TITLE
Question/improvements

### ISSUE THREAD

**Issue by usb248** [VodkaBears/Remodal#161]
Hi,

 Nice plugin ! I ask me why a very useful method like "content()" or "setContent()" doesn't exist ?
It wiil be very interesting if you implement an option to load external content in AJAX (This would expand the flexibility of your plugin !) and moreover, why not, display a pretty loading animation during loading like this very nice plugin for example (which let do many more things except the hash tracking) => [link](http://craftpip.github.io/jquery-confirm/#loadfromurl-advanced).

And if you are very motivated, implement an option to allow to set a timeout delay ([link] (http://craftpip.github.io/jquery-confirm/#autoclose)) ?

**Comment by VodkaBears** [comment]
>  I ask me why a very useful method like "content()" or "setContent()" doesn't exist ?

They are absolutely unnecessary. Аnalogy: $('[data-remodal-id=modal]').html(content);

> It wiil be very interesting if you implement an option to load external content in AJAX (This would expand the flexibility of your plugin !)

I don't think so. Unnecessary too. It is easy to implement. Analog:
```
$.get('path/to/data', function(data) {
  $('#container-id-in-modal').html(data);
});
```

> And if you are very motivated, implement an option to allow to set a timeout delay (link) ?
#83

> why not, display a pretty loading animation during loading like this very nice plugin for example (which let do many more things except the hash tracking) => link.

Same answer as above.

**Comment by usb248** [comment]
Hi,
 Yes, the method to change content is not very useful because the plugin need any repositioning with JS. The CSS do all (inline-block with a vertical align middle) I haven't seen that before to suggest this.

When is planned the new release with autoclose option ?

Thanks

**Comment by VodkaBears** [comment]
I agree with this opinion: https://github.com/VodkaBears/Remodal/issues/83#issuecomment-107424389
