### ISSUE TITLE
Remodal in Angularjs triggers new route

### ISSUE THREAD

**Issue by dutchman71** [VodkaBears/Remodal#163]
Hello,

first of all: awesome work, dude! Really love the responsiveness and flat look.

Here my question: I'm using Remodal with angular.js and the open method seems to be triggering a redirect to a new route in angular. How can I prevent that?

My code:

<div ng-click="openAddPostDialog()" class="btn btn-primary o-btn o-button-white pull-right">New Post</div>

	
	<div id="o-add-post-dialog" class="remodal" data-remodal-id="o-add-post-dialog" role="dialog" aria-labelledby="modal1Title" aria-describedby="modal1Desc" data-remodal-options="hashTracking: true, closeOnOutsideClick: true">
	  <button data-remodal-action="close" class="remodal-close" aria-label="Close"></button>
	  <div>
		<h2 id="modal1Title">Remodal</h2>
		<p id="modal1Desc">
		  Responsive, lightweight, fast, synchronized with CSS animations, fully customizable modal window plugin
		  with declarative state notation and hash tracking.
		</p>
	  </div>
	  <br>
	  <button data-remodal-action="cancel" class="remodal-cancel">Cancel</button>
	  <button data-remodal-action="confirm" class="remodal-confirm">OK</button>
	</div>

In the angular controller:
	 // Open Post Dialog
	 $scope.openAddPostDialog = function(){
		var inst = $('[data-remodal-id=o-add-post-dialog]').remodal();
		inst.open();
	 }

Thanks,

Chris

**Comment by dutchman71** [comment]
It seems to be related to appending the wrapper to the body. When I comment out remodal.js lines 515 to 530 the redirect does not occur.

**Comment by guideveloper** [comment]
Hi @dutchman71 did you ever fix this issue please?

**Comment by VodkaBears** [comment]
Is the reason in a hash?

**Comment by guideveloper** [comment]
No even if you remove the href it still redirects you

**Comment by zzeniou86** [comment]
data-remodal-options="hashTracking: false" should do the trick

**Comment by amilajack** [comment]
If you desperately want a fix, change the source by hardcoding in false on line 513:

![screen shot 2015-10-30 at 7 02 05 pm](https://cloud.githubusercontent.com/assets/6374832/10861345/da0cd37e-7f38-11e5-95ec-b3145438a18d.png)

**Comment by VodkaBears** [comment]
> If you desperately want a fix, change the source by hardcoding in false on line 513:

It isn't necessary.

Also, globals are useful in some cases like this one: https://github.com/VodkaBears/Remodal#globals

**Comment by brenolf** [comment]
I'm running on the same behaviour using v~1.0.6. I copied and pasted the example from the `hasTracking: false` example on README, but whenever I call `.open()` it redirects to the root.
