### ISSUE TITLE
Bower install fails due to description being too long

### ISSUE THREAD

**Issue by jmfarina** [VodkaBears/Remodal#165]
When attempting to install, bower (latest stable version, 1.4.1) fails and reports: "The description is too long. 140 characters should be more than enough". Remodal's description in bower.json is 154 characters long.

**Comment by VodkaBears** [comment]
![2015-08-04 00-38-14 www bash 181x48](https://cloud.githubusercontent.com/assets/1700334/9048350/2adc6ea0-3a41-11e5-828b-b86e470ff993.png)

**Comment by jmfarina** [comment]
Hello,
I'm new to bower so I'm not quite sure how all this plays along, but it seems that some bower 1.4.1 versions use bower.json 0.4.0 (https://github.com/bower/json/blob/0.4.0/lib/json.js) and others, like the one I have that's failing, use 0.5.0, which is the one in which they introduced this validation: https://github.com/bower/json/commit/fd39c5d2197ed21971dc4f1233a36473241965f7#diff-3f9d46363ce3a43200a9dfa6e3c9cf28.
There's an issue filed in bower.json pleading for a reconsideration on this validation: https://github.com/bower/json/issues/22. But in the meanwhile, with version 0.5.0 of said library, it's not possible to install remodal (as well as other libraries, I gather).

**Comment by VodkaBears** [comment]
https://github.com/VodkaBears/Remodal/commit/d893486d58e65bffb3583becd2e8fe3eaf57bb73
