### ISSUE TITLE
How to get a confirmation modal?

### ISSUE THREAD

**Issue by KoningVoetbal** [VodkaBears/Remodal#166]
Hello,

I try to make a delete button with a confirmation modal, I have the following code:

$('#delete_button').click(function() {
    $('[data-remodal-id = modal-delete]').remodal().open();
    $(document).on('confirmation', '#modal-definitief-verwijderen', function () {
        alert('Confirmation button is clicked');
    });
    $(document).on('cancellation', '#modal-definitief-verwijderen', function () {
        alert('Cancel button is clicked');
    });
});

<div class="remodal" data-remodal-id="modal-delete">
    <div class="h1_modal">DELETE CONFIRMATION</div> 
    <div class="p_modal">Are you sure you want to delete this record?</div>
    <button data-remodal-action="cancel" class="remodal-cancel">Cancel</button>
    <button data-remodal-action="confirm" class="remodal-confirm">OK</button>
</div>

The modal is opening when I click on the button with the ID #delete_button but when I choose Cancel or OK, I don't see any alert.

How can I get this working?

Kind regards,

Arie

**Comment by VodkaBears** [comment]
Please, see examples folder in the repo. Everything works there.
