### ISSUE TITLE
Enhancement: optional window.location.replace() on remodal.close()

### ISSUE THREAD

**Issue by pavsid** [VodkaBears/Remodal#167]
When hashTracking is enabled, and a remodal is closed, when the user clicks the back button the remodal will re-open again.

This might not be the desired action, and so an optional parameter to the remodal.close() method would be good which would in effect replace the current URL (remodal open), e.g. www.example.com/#remodal, with the new URL (remodal closed) e.g. www.example.com/# so that when the user clicks back the remodal does not open again.

**Comment by VodkaBears** [comment]
If you really want to show it once, you should disable the hash tracking and open it if something happens(pageload, hashchange, etc).

**Comment by pavsid** [comment]
@VodkaBears but you might want the hashtracking functionality usable, until you manually close the modal with `remodal.close(true)` when the history entry is replaced and so the modal can't be re-opened by navigating.

I would have thought that approach is much easier to implement than manually coding the hash tracking events..?
