### ISSUE TITLE
jQuery minimum version requirement

### ISSUE THREAD

**Issue by kalenjordan** [VodkaBears/Remodal#174]
Hey there, thanks for this awesome project.  I'm trying to figure out what the minimum jQuery version requirement is and had some trouble hunting that down.  I seem to be running into some issues with a site that's on jQuery 1.4.

**Comment by VodkaBears** [comment]
I've tested it in the quite new versions.

**Comment by kalenjordan** [comment]
@VodkaBears gotcha.  So it probably wouldn't surprise you if it wasn't compatible with 1.4?

**Comment by VodkaBears** [comment]
I am more surprised by your jQuery version :D

**Comment by VodkaBears** [comment]
jQuery 1.4 does not support this method: http://api.jquery.com/on/.

**Comment by kalenjordan** [comment]
Cool gotcha.  And by the way it's not my personal project.  I have a customer on an older version and I don't have too much direct control over getting it updated. 

Thanks again for the quick feedback and for this amazing project!
