### ISSUE TITLE
Modifier applied only on remodal-bg and remodal-overlay

### ISSUE THREAD

**Issue by zzeniou86** [VodkaBears/Remodal#183]
Hi all,
I noticed that the remodal modifier does not apply to all remodal classes (i.e. .remodal) in the following use case where you apply a modifier at a later time.

Example code:
```html
  <div data-remodal-id="imamodal"> hello</div>
```

```javascript
var remodal = $('[data-remodal-id= imamodal]').remodal();

//at a later time via user input 
remodal.settings.modifier="test-modifier";
remodal.open();
```

**Comment by VodkaBears** [comment]
No. See examples.

`remodal.settings.modifier`. Don't use undocumented fields. https://github.com/VodkaBears/Remodal#initialization-with-javascript

**Comment by zoxon** [comment]
Can you add support for `data-remodal-modifier` attribute?
