### ISSUE TITLE
IOS 9 safari scaling issues

### ISSUE THREAD

**Issue by mtorniai** [VodkaBears/Remodal#184]
On IOS 9 Safari the modal goes crazy. The example on the remodal website (http://vodkabears.github.io/remodal/) zooms out so large it doesn't fit the screen. I also get weird infinite zoom loop happening on my app where I use remodal on top of a canvas that also scales according to the innerwidth on resize. It only seems to happen sometimes for example when returning from screen lock. For some reason when it works it works better on my app than on the remodal website. Lots of meat there though to see exactly what causes it. I haven't changed any of the css or js included. I do also load bootstrap.

**Comment by nevitas** [comment]
Confirm problems with iOS 9 Safari.

[image](https://cloud.githubusercontent.com/assets/5923148/10313402/172136ae-6c58-11e5-8297-479734050607.png)
