### ISSUE TITLE
hashTracking - Modal Still Opens w/ Hash Using data-remodal-target Attribute

### ISSUE THREAD

**Issue by curtismorte** [VodkaBears/Remodal#185]
In the documentation, it's stated that:

To open the modal without the hash, use the data-remodal-target attribute.
```
<a data-remodal-target="modal" href="#">Call the modal with data-remodal-id="modal"</a>
```

After experimenting with this on my own, it still appears that the href is being added to the page. Even if you change the href attribute to href="javascript:void(0)", the hash is still added.

I was able to get around this by changing the window.REMODAL_GLOBALS.DEFAULTS.hashTracking value to false.

**Comment by VodkaBears** [comment]
yep, `data-remodal-targer` just opens the modal with the given id, so you should set `hashTracking` to false in the settings before.
