### ISSUE TITLE
Crawlable anchors

### ISSUE THREAD

**Issue by ursbraem** [VodkaBears/Remodal#186]
I would like Google to index all those nice remodals individually by their anchor.

According to https://support.google.com/webmasters/answer/174992?hl=en, the starting point seems to get a "hashbang" into the URL. `mysite.com/#!myanchor`. I've tried simply adding that to the code, like `<a href="#!myanchor">` and `data-remodal-id="!myanchor"`, but that wouldn't work out of the box. Neither using `%21` instead of `!`.

Not sure if the entire operation makes sense though! What's your opinion on this?

**Comment by VodkaBears** [comment]
It is absolutely easy to fix.

**Comment by ursbraem** [comment]
You are too good. Thank you very much!
