### ISSUE TITLE
Tabindex only on form elements inside the opened modal window

### ISSUE THREAD

**Issue by martinpesout** [VodkaBears/Remodal#19]
Hi,

I have webpage with many HTML form elements. Each element has own tabindex attribute starting from 1. Than I have modal popup with another form elements inside with tabindex attribute starting from 1. I thought that if I refocus on the first element in the modal window, problem will be solved, but form elements on the backround are still active by pressing TAB key. 

Is there any way how can I disabled form elements on the background?

Thanks for your advice ;-)

**Comment by PradeepNair1988** [comment]
Hi ,

I encountered the same issue and below logic helped me to resolve the issue.

//  On the open of Modal window
//Updating the tabindex value to another attribute and make the tabindex =-1 which is the background
 var inputs = $(document).find('select, input, textarea, button, a').filter(':visible');
                $(inputs).each(function(){
                    var tbindex=$(this).attr("tabindex");
                    $(this).attr("data-index",tbindex);
                    $(this).attr("tabindex",-1);        
                });
//  On the close of Modal window
//Re-update the tabindex value to from the attribute which you have set when you are opening the modal window.
  var inputs = $(document).find('select, input, textarea, button, a').filter(':visible');
                $(inputs).each(function(){
                    var tbindex=$(this).data("index");
                    if(tbindex){
                        $(this).attr("tabindex",tbindex);
                    }       
                });
