### ISSUE TITLE
Remodal No Longer Opening

### ISSUE THREAD

**Issue by buschschwick** [VodkaBears/Remodal#190]
So I'm using Remodal on an upcoming project and it was working before and now all of a sudden its firing really strange. I'm not getting any errors and I've disabled all JS beside Remodal and still not loading correctly (I've since re-enabled other JS).

Any thoughts? (Click the 'Sign Up For Our Newsletter' in the header to fire it). It tries to fire, and flashes the overlay and then you have to click twice to gain control of the page again.

http://ther29.com/2015/healthcorps/

I've been using Remodal for quite some time and this is the first time I've run into something like this. Thanks!

**Comment by pablovilas** [comment]
Hi, there is no element with id 'modal'

**Comment by buschschwick** [comment]
@pablovilas

My apologies, I had it removed currently for trouble shooting. I put the HTML back in, and if you were to test it now, you would see what is happening.

**Comment by buschschwick** [comment]
@pablovilas

If you inspect element there is no trace of the element, which is really odd. If you view source you can see it (right above the footer)... For some reason the HTML seems to be getting eaten/ignored?

**Comment by VodkaBears** [comment]
You removed this rules (https://github.com/VodkaBears/Remodal/blob/master/src/remodal-default-theme.css#L18-L21) and didn't make any workarounds. https://yadi.sk/i/jAyxczIJjx8uE

**Comment by buschschwick** [comment]
Thats the thing, I'm not removing them - I'm pulling my CSS/JS straight from the DIST folder of the Remodal node package for testing purposes and I'm still getting strange results. I do see changing the opacity to 1 gives me the colored background, but I'm still lost as to why the HTML for the Remodal seems to be vanishing. 

![screen shot 2015-10-23 at 9 49 40 am](https://cloud.githubusercontent.com/assets/9441913/10699414/7eb046aa-796b-11e5-9174-cec05c095664.png)

**Comment by VodkaBears** [comment]
In the previous scrrenshot, i didn't pay attention that there are styles of v0.x. See: https://yadi.sk/i/jAyxczIJjx8uE

**Comment by VodkaBears** [comment]
Mixed styles: http://ther29.com/2015/healthcorps/wp-content/plugins/staff-grid/css/jquery.remodal.css?ver=ef0d8824bd6d8c657c55a80132386875

**Comment by buschschwick** [comment]
AH! YES! Thank you so much, we were using a custom plugin and it had an old Remodal version built in. Removing the Remodal from the plugin fixes the issue. I truly appreciate your help and support.
