### ISSUE TITLE
How to open an external URL in the modal?

### ISSUE THREAD

**Issue by rive46** [VodkaBears/Remodal#193]
Hi guys,

Im a noob in this world and my English is bad.
I'm making a web using MVC and I would like to use something like this:
```
<a href="views/modalView.html">
```
Instead this:
```
<a href="#modal">
```
Because this opens a hidden div that is in the same *.html

I hope I explained it well.
Thank you so much

**Comment by rive46** [comment]
Well, I solved this with
```
<a href="views/modalView.html#modal">
```
But the problem is when I click on the link, the URL goes to "http://localhost:3000/views/modalView.html#modal" and I can't see the index.html content under the overlay. Then, when I click on X button to close the modal, the URL goes to "http://localhost:3000/views/modalView.html#" and I have to click on previous button to go back.

**Comment by VodkaBears** [comment]
You are doing something strange.
