### ISSUE TITLE
On Windows Phone 8 remodal popups did not block document scroll

### ISSUE THREAD

**Issue by fantarama** [VodkaBears/Remodal#195]
To reproduce the issue create a simple page with scrolling content ad a remodal popup. When the popup is open it seem all ok (the background is ok and the popup is right centered) but I can still scroll the page and the popup overlay scroll with the page.

My device screenshot:

![wp_ss_20151116_0002 1](https://cloud.githubusercontent.com/assets/7951123/11179647/35d778b6-8c55-11e5-8854-6d37a9cebaec.png)

**Comment by fantarama** [comment]
Solved, just add this style:

    html.remodal-is-locked {
        touch-action:none;
    }

**Comment by SimoneBuono** [comment]
perhaps body { overflow:hidden;} would fix it
