### ISSUE TITLE
Closing the Video when the modal is close

### ISSUE THREAD

**Issue by akramgassem** [VodkaBears/Remodal#197]
I have use Remodal to insert a embed Youtube video but when you close the modal, the video still playing. Please any solution to prevent closing video when the modal is closed.

**Comment by VodkaBears** [comment]
Clear content.

**Comment by DexX39** [comment]
How to clear content ? No API functions ? Ty.

**Comment by mkkokay** [comment]
Here is a trash fix for you! Attach this function to your close button. 
function endVideo()
	{
        var video = $("#divID iframe").attr("src");
        $("#divID iframe").attr("src","");
        $("#divID iframe").attr("src",video);
}

**Comment by rubelmiah** [comment]
Best solution.
Try this code:

```
$(document).on('closed', '.remodal', function (e) {
    var src = $(this).find('iframe').attr('src');
    $(this).find('iframe').attr('src', '');
    $(this).find('iframe').attr('src', src);
});
```
