### ISSUE TITLE
Add "map" file to the distribution files

### ISSUE THREAD

**Issue by meglio** [VodkaBears/Remodal#206]
Please may I ask you to add a `.map` file and link to it from the `.min` file.

**Comment by VodkaBears** [comment]
You can generate sourcemaps from the sources. Defenetely, sourcemaps in the repo are not very well.

**Comment by meglio** [comment]
What's wrong with distributing .map files? JQuery, for example, does [distribute .map files](http://jquery.com/download/).

**Comment by VodkaBears** [comment]
jQuery is not synonymous with good practice.
