### ISSUE TITLE
Why the remodal instance removes the jquery methods?

### ISSUE THREAD

**Issue by lemagnetic** [VodkaBears/Remodal#209]
I would like to do this:

```sh
$('.remodal').remodal().on('opened', callback);
```

or this

```sh
var remodalInst = $('.remodal').remodal();
remodalInst.on('opened', callback);
```

:/

**Comment by usb248** [comment]
Firstly, callback are on $(document) (the descendants of the selected elements .remodal), not on the remodal instance... (Read the doc ...).

```javascript
$(document).on('opened', '.remodal', function () {
  console.log('Modal is opened');
});
```

The plugin return remodal instance, so you can call public method. 

In the jquery documentation : The .on() method attaches event handlers to the **currently selected set of elements in the jQuery object**

If you want to keep your code : 

```javascript
var remodalInst = $('.remodal').remodal();
$(document).on('opened', '.remodal', function () {
  callback();
});
```
