### ISSUE TITLE
Close after page refresh

### ISSUE THREAD

**Issue by mosesmc52** [VodkaBears/Remodal#214]
Hi, 

Everytime I refresh a page after the remodal box was launched the modal box is in open state. How do I default the modal box to a close state even after a page refresh?

**Comment by dankreiger** [comment]
I'm also having this issue

**Comment by richtestani** [comment]
Use the hashTrack options your modal window. data-remodal-options="hashTracking: false, closeOnOutsideClick: false"

As long as you are calling remodal normally (event based), this will work. if you call it from an instance, options do no seem to work (which is the issue I present in another issue).

**Comment by rolivav** [comment]
I am using remodal right now like this, and it works.
```
var modalSms = this.$('[data-remodal-id=modalSms]').remodal({
			'hashTracking': false,
                        'closeOnOutsideClick': false
		});
modalSms.open();
```
