### ISSUE TITLE
Loading modal from ajax

### ISSUE THREAD

**Issue by anthonysbrown** [VodkaBears/Remodal#22]
Hey hows it going, First of all thanks for the great work on this plugin its amazing and its the best looking modal for responsive design.

I'm attempting to use this for our wordpress file document manager but its ajax based so I would be loading the modal boxes in dynamic ajax pulled content. I'm finding that the modal will not open when pulled from an ajax request.  So what I'm doing is making the request then appending the pulled html to a div. Do you know of a work around for this? I'm guessing its because the html and modal is added after remodal initiates

**Comment by thethakuri** [comment]
Upto how many modals per page is ideal ? I am adding them dynamically and I am afraid too many will slow the webpage down ?

**Comment by iDentity1337** [comment]
I've used this and worked perfectly for first time, but after closing the modal and trying to reopen, nothing happens.
