### ISSUE TITLE
Prevent background scrolling on iOS devices

### ISSUE THREAD

**Issue by kaplanmichael** [VodkaBears/Remodal#225]
Is there currently a way to prevent the page that _calls _(and is visible underneath) the modal from scrolling?  For instance, on iOS devices, when you open a remodal, you can still scroll the underlying page behind it by swiping your finger.   I didn't see anything in the docs.  Thank you so much for your assistance.

**Comment by VodkaBears** [comment]
No, there isn't a good solution.
