### ISSUE TITLE
How to use remodal with webpack?

### ISSUE THREAD

**Issue by panteng** [VodkaBears/Remodal#229]
Below is my code. I use Webpack to bundle them.

    require('remodal/dist/remodal.css');
    
    var $ = require('jquery');
    
    require('remodal');
    
    module.exports = {
        bind: function () {
            var _this = this;
    
            _this.instanse = $(_this.el).remodal();
        },
        unbind: function () {
            var _this = this;
    
            _this.instance.destroy();
        }
    };

But there's something wrong.
The console says:
    
    Uncaught TypeError: $(...).remodal is not a function

Could anyone help me? Thanks.

**Comment by rdpascua** [comment]
What I have is this

```
var $ = require('jquery');
import 'remodal'

```

**Comment by panteng** [comment]
@rdpascua 
Thx.

I found the reason. It was because my NPM is outdated.

Npm v.2.x.x installs nested dependencies. That means I have two jquery packages in my node_modules folder. One is for Remodal (node_modules/remodal/node_modules/jquery/), the other is for the whole app(node_modules/jquery).

So when I call `var $ = require('jquery')`, actually I am not requiring the same jquery that Remodal requires. That's why the chrome console says `Uncaught TypeError: $(...).remodal is not a function`

**Comment by panteng** [comment]
@VodkaBears 

But I still think there's something wrong when I use Remodal with Webpack.
Remodal always thinks I am using AMD. But actually I am using CommonJS.

So I looked up the source code of Remodal. And I found Remodal use this way to determine which module style I am using:

    if (typeof define === 'function' && define.amd) {
        define(['jquery'], function($) {
          return factory(root, $);
        });
      } else if (typeof exports === 'object') {
        factory(root, require('jquery'));
      } else {
        factory(root, root.jQuery || root.Zepto);
      }

But when using Webpack, `define` is a valid function and `define.amd` does exist. So the first `if` will always be true.

Webpack official page has a instruction for this.

http://webpack.github.io/docs/shimming-modules.html#broken-amd

**Comment by andrebautista** [comment]
I'm loading my jQuery from a CDN using the $script loader and then requiring remodal after the dependency, jquery and `$`, have been defined.
```
$script("https://code.jquery.com/jquery-1.12.3.min.js", function() {
    window.fcJq = jQuery.noConflict(true);
    requirePackage("jquery");
    var remodal = require('remodal');
});
```

**Comment by panteng** [comment]
@andrebautista Thank you. This problem has been solved.
