### ISSUE TITLE
blurry text when opening modal window

### ISSUE THREAD

**Issue by tanimoto-true** [VodkaBears/Remodal#280]
I'm using ```remodal ver 1.1.1(current version)``` and ```chrome ver 57(current version)```

When modal opens, texts are blurry.
Once I move mouse outside the window, it becomes clear.

Any tips to fix it??

**Comment by luk3nukem** [comment]
The only way I found to fix this was to change the animation duration in the theme CSS.  If you're using remodal-default-theme.css, change lines 69 and 70 from 0.3 to 0.1 seemed to stop it getting stuck at the end of the transition.  I hope this helps.

**Comment by tanimoto-true** [comment]
Thanks for the tips!
I close this issue.
