### ISSUE TITLE
Issue with form submission

### ISSUE THREAD

**Issue by c316** [VodkaBears/Remodal#37]
My issue is similar to https://github.com/VodkaBears/Remodal/issues/29, but I'm using Meteor and in that the form isn't being submitted by post. There is a submit form event handler setup. This event handler never gets used because remodal is doing something else fist. I've tried the solution posted in issue 29, but that doesn't work either. 

Also, if I remove the modal and just use the form on a page it submits just fine. Any advice as to where I might look. I've already read through all the docs and tried many different combinations from them to try to resolve this. Thanks

**Comment by VodkaBears** [comment]
Reopen, if still need a help.
