### ISSUE TITLE
Content behind overlay visible

### ISSUE THREAD

**Issue by paulcredmond** [VodkaBears/Remodal#44]
As you have documented, there are 2 options for dealing with overflow if you have set HTML to have `height: 100%`.

Under certain circumstances neither of these options are working well in my testing so far. Normally, with a HTML set to `height: 100%;` the screen jumps to the top before opening the lightbox - which isn't ideal. Using the alternative `html, body { overflow: auto !important; margin: 0; }` will stop the page jumping from the top, but on touch devices you can then scroll the content behind the modal, which doesn't happen with the first option.

With either option set there is a problem with the content behind the overlay becoming visible, this happens when the modal is tall enough to move offscreen when a touch device on-screen keyboard is brought up. When the keyboard is closed by tapping the `.remodal` box part of the background becomes visible.

The below is taken on an iPad mini retina and happens with both Safari and Chrome:

![image1](https://cloud.githubusercontent.com/assets/2063873/4594870/8ad58ad2-5093-11e4-9e89-490b19c3c039.jpg)
![image2](https://cloud.githubusercontent.com/assets/2063873/4594869/8acfe226-5093-11e4-953b-045e80646a28.jpg)

**Comment by gcosgreave** [comment]
I am still experiencing this issue in version v1.0.6. If I revert to version 0.4.0 then it works but then my img breaks which is why I upgraded in the first place. Any help would be great
