### ISSUE TITLE
Open automatically on page load

### ISSUE THREAD

**Issue by madhuco** [VodkaBears/Remodal#52]
Is there a way to get the modal to automatically open on page load. 

Thanks!

**Comment by bikify** [comment]
Exactly this is the code for pageLoad for Remodal.
**html:**

> <div class="remodal-bg">
     <div class="remodal" data-remodal-id="modal">
        <h1>Remodal</h1>
        <p>
            Flat, responsive, lightweight, fast, easy customizable modal window plugin
            with declarative state notation and hash tracking.
        </p>
        <p>
            Minified version size: ~4kb
        </p>
        <br>
        <a class="remodal-cancel" href="#">Cancel</a>
        <a class="remodal-confirm" href="#">OK</a>
    </div>
</div>

**JS**:

> $(function(){ 
    var inst = $.remodal.lookup[$('[data-remodal-id=modal]').data('remodal')];
    inst.open();
});

checkout this  [fiddle](http://jsfiddle.net/sxb89Lod/)
