### ISSUE TITLE
on "close" is fired when "confirm" is clicked.

### ISSUE THREAD

**Issue by Pathsofdesign** [VodkaBears/Remodal#65]
I'm not sure if this is a bug or not, but when you click to confirm the modal, both the 'confirm' and 'close' is fired. This makes it difficult to run different tasks in my listeners if the modal was closed via clicking the 'X'. 

Any ideas? Thanks!

**Comment by VodkaBears** [comment]
https://github.com/VodkaBears/Remodal/commit/7a1fb50a6e06c06570ab54e1a0aabc282e928800
