### ISSUE TITLE
Switch to on instead of bind

### ISSUE THREAD

**Issue by ururk** [VodkaBears/Remodal#71]
Instead of using bind:

https://github.com/VodkaBears/Remodal/blob/master/src/jquery.remodal.js#L209

would it be possible to switch to .on? Then the plugin could simply look for any element with the remodel-cancel, -confirm, etc... class when the element is clicked, rather than when the plugin is loaded. This way, dynamically added buttons would be supported.

**Comment by VodkaBears** [comment]
Yes, `.on` is preferred. It's time to switch on it.
Pull request? :smile:

**Comment by ururk** [comment]
Sure, will do!

**Comment by Ashot-KR** [comment]
I replaced `.bind` with `.on` here https://github.com/VodkaBears/Remodal/pull/70#commits-pushed-c562908

**Comment by VodkaBears** [comment]
> I replaced .bind with .on here #70 (commits)

Separate PR would be better.

**Comment by VodkaBears** [comment]
Done.
