### ISSUE TITLE
Mandatory modals (should never close)

### ISSUE THREAD

**Issue by Fuffi** [VodkaBears/Remodal#74]
Is it possible to have a modal without close button and that will not close if clicking anywhere?

**Comment by Sicria** [comment]
I believe it's something like this.
```
data-remodal-options="closeOnConfirm: false, closeOnCancel: false, closeOnEscape: false, closeOnAnyClick: false"
```

**Comment by Fuffi** [comment]
I did that, but I had to add this CSS to make the X button disappear, would be good to have a single option to make a modal mandatory

      .remodal-close {
        display: none;
      }

**Comment by Sicria** [comment]
You can do something like this, if you're wanting to remove the button completely.
```
$.remodal.lookup[$('[data-remodal-id=modal]').data('remodal')].$closeButton.remove();
```

**Comment by Fuffi** [comment]
Thank you, I suggest having an option like {mandatory: true} to add to the data attributes would be cool, anyway thank you again
