### ISSUE TITLE
Open Modal Window then Back Button...

### ISSUE THREAD

**Issue by respectyoda** [VodkaBears/Remodal#76]
This is one incredible find and love it! However, there is one weird bug that needs to be squashed. 

Let's say you have a button on a certain page and when you click on it, the modal window appears! You close it. Now, when you click on the Back button on the browser to go to the previous page you viewed, the modal window comes up which should not happen. 

Is there a fix for this??

**Comment by VodkaBears** [comment]
Hello, i suggest you to set `hashTracking: false`(https://github.com/VodkaBears/Remodal#hashtracking)

**Comment by respectyoda** [comment]
Thank you for your prompt response. Ah, that makes sense. I shall put it to the test and hopefully, the bug will be squashed. :)

**Comment by respectyoda** [comment]
The bug was successfully squashed. Mucho gracias.

Also, are there any features you plan to add to this "plugin"?

**Comment by VodkaBears** [comment]
> Also, are there any features you plan to add to this "plugin"?

Yes, it happens all the time, but i always try to save compatibility with previous versions.
