### ISSUE TITLE
Ajax и динамически добавленные кнопки Cancel, Confirm...

### ISSUE THREAD

**Issue by zensimilia** [VodkaBears/Remodal#80]
Была потребность загружать в модальное окно динамически через Ajax разные формы, где-то были кнопки Cancel, где-то нет. Но после добавления они не работали ( пришлось изменить пару строк в коде плагина:

```
remodal.$cancelButton.bind("click." + pluginName, function(e) {
```

заменил на:

```
$(document).on("click." + pluginName, remodal.$cancelButton.selector, function(e) {
```

и так все остальные "бинды" - все заработало )

**Comment by VodkaBears** [comment]
https://github.com/VodkaBears/Remodal/commit/5ff9fd63d0dde40c5a0ebc94cdd87d368b59d290
