### ISSUE TITLE
Slow closing is generating wrong behavior

### ISSUE THREAD

**Issue by sebrojas14** [VodkaBears/Remodal#81]
Hi,

Great library! I'm having a serious problem because of the slow closing of the remodals. When I close a remodal there's a period when the remodal is hidden but still displayed (the period betwwen the close action and the closed event), so if I touch again the screen, my app is taking a click over an element in the remodal. Additionaly, that behavior generates that the close method is ignored after close and open quickly sometimes. Maybe the first thing to do after close action has to be display:none on remodal-wrapper and remodal-overlay?

Thank you for your attention

**Comment by VodkaBears** [comment]
Hello. Yes, when a remodal instance is opening, you can't close it, if it is closing, you can't open it. If you want to change timeouts of the animation, just modify CSS styles.

https://github.com/VodkaBears/Remodal/blob/master/src/jquery.remodal.css#L100-L103
https://github.com/VodkaBears/Remodal/blob/master/src/jquery.remodal.css#L117-L120
https://github.com/VodkaBears/Remodal/blob/master/src/jquery.remodal.css#L142-L145
