### ISSUE TITLE
Close-Button gone after closing and re-opening

### ISSUE THREAD

**Issue by kevingrabher** [VodkaBears/Remodal#82]
If I open a modal, I have the close button as usual.
I close the modal, open it again - close button is gone.

**Comment by VodkaBears** [comment]
Hm. Is it in the DOM? Can you look plz with devtools?

**Comment by kevingrabher** [comment]
I open the modal the first time, it's visible and in the DOM.
I close the modal - still in the DOM.
I open the modal again - it's gone from the DOM

**Comment by VodkaBears** [comment]
Are you sure, that your code does not remove it?  Remodal only adds the close-button(https://github.com/VodkaBears/Remodal/blob/master/src/jquery.remodal.js#L226).

**Comment by kevingrabher** [comment]
Okay, this was a user issue.
Since the close button is put into the div I'm calling, when the i modify the div via .html() the delete-button falls out. I suppose it happens only the 2nd time because the first time because the modal fires after my own .html() the first time.
