### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by respectyoda** [VodkaBears/Remodal#83]
I thought of a new feature this Remodal plugin should have. It should have the option to close the modal after a certain time of X seconds (of course, it probably will be measured in milliseconds).

**Comment by VodkaBears** [comment]
Hm. Why not? I've labeled it.

**Comment by pixeline** [comment]
Why not? 
1./ bigger codebase
2./ bad ux practice: let the user control the experience. Do you really want to let people create modals that cannot be closed for X seconds? The Internet is already so full of those modals that pop up on blogs with a big call-to-action (and a very small close button hidden somewhere). Let's not make it worse.
3./ It's easy enough to do when you really need it.

If argument 2 does not convince you, please consider argument 1 and 3.
