### ISSUE TITLE
Why is closeButton appended? Can I prevent that?

### ISSUE THREAD

**Issue by CollinY2K** [VodkaBears/Remodal#84]
I do not want to have the $closeButton appended in my modal as I already include my own. However, I don't see a way to prevent it since it appears to be appended in the jQuery. Am I missing something or do I just need to remove that line in the jQuery source?

**Comment by VodkaBears** [comment]
OK, too many issues about the close button, i will make it optional, a bit later.

Set `display: none` in the styles.

**Comment by AlecRust** [comment]
+1 this should be an option
