### ISSUE TITLE
Font import fails for https

### ISSUE THREAD

**Issue by razor-x** [VodkaBears/Remodal#86]
This line will throw an error and refuse to load the font when the page is served over https (at least in Chrome): https://github.com/VodkaBears/Remodal/blob/74807e518e908f69fa62f8df790a749cfd157c9d/src/jquery.remodal.css#L1

Personally I don't think the font should be hard coded like this: if I don't want to use Exo this still costs a page request. Also consider that if I'm using something like Web Font Loader to handle all of my async font loading I want to handle loading Exo the same way and not via CSS import.

**Comment by VodkaBears** [comment]
#85

**Comment by VodkaBears** [comment]
Will be removed in 0.7.0.
