### ISSUE TITLE
How to auto-scroll to top of long modal?

### ISSUE THREAD

**Issue by shkolnik** [VodkaBears/Remodal#87]
I'm using Remodal to display a fairly long modal dialog which will require scrolling on the majority of screens. I love Remodal's support for scrolling the modal while keeping the background page frozen... it's working great and is one of the reasons I chose this library.

The issue I'm having is that when the modal is initially displayed, it is vertically centered in the window so the top of the dialog is cut off. Is there a way automatically scroll to the top of the modal when it is displayed?

Thanks!

-James

**Comment by VodkaBears** [comment]
Try this:
```js
$(document).on("open", ".remodal", function () {
  setTimeout(function() {
   $('.remodal-wrapper').scrollTop(0);
  }, 30);
});
```

**Comment by VodkaBears** [comment]
I will make a patch later.
