### ISSUE TITLE
Jumping to middle of long page on modal show

### ISSUE THREAD

**Issue by constantm** [VodkaBears/Remodal#88]
I'm using Bootstrap 3 along with Remodal. When I open the modal it jumps down to the middle of the page instead of staying where it currently is. Is this a known issue, and is there a way around this?

Update: A fix we're using now to prevent this:

```
function open_remodal_nojump(modal) {
    x=$(document).scrollTop();
    modal.open();
    $(document).scrollTop(x);
}
```

**Comment by VodkaBears** [comment]
What version do you use?

**Comment by constantm** [comment]
0.6.3 - updated yesterday.

**Comment by VodkaBears** [comment]
I have an assumption that you have an anchor on your page. And when the hash changes, it jumps to the specified id. `#info -> <div id="info"></div>`

https://github.com/VodkaBears/Remodal/blob/master/src/jquery.remodal.js#L368

**Comment by constantm** [comment]
You sir, are 100% correct.
