### ISSUE TITLE
How to make modal open when page opnes ( ie don't have to click)

### ISSUE THREAD

**Issue by samrae7** [VodkaBears/Remodal#89]
Hi. Sorry for basic question but can you tell me how to set it up so that the modal opens when the page loads ( ie not only on click)? Thanks

**Comment by CollinY2K** [comment]
You could just call the modal open on document ready, like so:

```
$( document ).ready(function() {
  $('[data-remodal-id=modal]').remodal().open();
});
```

**Comment by samrae7** [comment]
Thanks!
