### ISSUE TITLE
Is it possible to press enter to confirm modal?

### ISSUE THREAD

**Issue by tylerlong** [VodkaBears/Remodal#92]
I'd like to press enter to confirm modal, just like pressing esc to close modal. Is it possible?

Thank you.

**Comment by tylerlong** [comment]
I have found a way to do it, not a general way though.

In my modal there is a text field with ID `#text-field`, and the confirm button's ID is `#confirm-btn`.

User enters something in the text field, then press enter to confirm the modal:

```javascript
$('#text-field').keyup(function(e) {
  if(e.which == 13) {
     $('#confirm-btn').click();
  }
});
```

Feel free to close this issue.

**Comment by VodkaBears** [comment]
Ok, there are no options for this behavior, yet...
