### ISSUE TITLE
Calling an image with remodal

### ISSUE THREAD

**Issue by Greg-J** [VodkaBears/Remodal#99]
I'm not sure if this is a feature request or a question regarding current functionality, but it seems rather fairly common practice with other modal plugins that you can simply attach the modal functionality to a link and it'll load that target in the modal. Whether that be a #target, or a url that gets loaded in an iframe, or a resource location (such as an image).

Does remodal offer this kind of flexibility, or are you required to have the modal content on the page?

**Comment by VodkaBears** [comment]
> Does remodal offer this kind of flexibility, or are you required to have the modal content on the page?

You can put any content into the modal at any time, you can put an image or an iframe, no matter what. You can customize any element by using CSS. Remodal is absolutely flexible.

```js
$('[data-remodal-id=modal]').html('...content...');
```
